// <auto-generated />
using System;
using BaggageService.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BaggageService.Migrations
{
    [DbContext(typeof(AeroScanDataContext))]
    [Migration("20260422151458_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Aggregates.Bags.ArrivalBag", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ArrivalBaggageStatus")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.Property<string>("CheckedWeight")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.Property<int?>("ContainerId")
                        .HasColumnType("integer");

                    b.Property<int>("FlightPassengerId")
                        .HasColumnType("integer");

                    b.Property<int?>("HhtId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTransfer")
                        .HasColumnType("boolean");

                    b.Property<string>("RushReason")
                        .HasColumnType("text");

                    b.Property<string>("SourceAirportCode")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<char>("SourceIndicator")
                        .HasMaxLength(1)
                        .HasColumnType("character(1)");

                    b.Property<string>("TagNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("FlightPassengerId");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("FlightPassengerId"), new[] { "TagNumber" });

                    b.HasIndex("TagNumber");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("TagNumber"), new[] { "FlightPassengerId" });

                    b.ToTable("ArrivalBags", "bags");
                });

            modelBuilder.Entity("Domain.Aggregates.Bags.ArrivalBagEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BagId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("DeviceId")
                        .HasColumnType("integer");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("EventTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("MessageId")
                        .HasColumnType("bigint");

                    b.Property<string>("UserName")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("BagId");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("BagId"), new[] { "EventId", "Description", "UserName", "EventTime" });

                    b.ToTable("ArrivalBagEvents", "bags");
                });

            modelBuilder.Entity("Domain.Aggregates.Bags.ArrivalFlightPassenger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<int>("FlightId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsTransfer")
                        .HasColumnType("boolean");

                    b.Property<string>("PassengerName")
                        .IsRequired()
                        .HasMaxLength(55)
                        .HasColumnType("character varying(55)");

                    b.Property<string>("Seat")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("SecurityNumber")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("SequenceNumber")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.HasKey("Id");

                    b.HasIndex("FlightId");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("FlightId"), new[] { "Id" });

                    b.HasIndex("FlightId", "SecurityNumber")
                        .IsUnique()
                        .HasFilter("\"SecurityNumber\" IS NOT NULL");

                    b.HasIndex("FlightId", "SequenceNumber")
                        .IsUnique()
                        .HasFilter("\"SequenceNumber\" IS NOT NULL");

                    b.ToTable("ArrivalFlightPassengers", "bags");
                });

            modelBuilder.Entity("Domain.Aggregates.Bags.DepartureBag", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<char?>("AckRequest")
                        .HasColumnType("character(1)");

                    b.Property<bool>("AuthorityToLoad")
                        .HasColumnType("boolean");

                    b.Property<bool>("AuthorityToTransport")
                        .HasColumnType("boolean");

                    b.Property<string>("CheckedWeight")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.Property<int?>("ContainerId")
                        .HasColumnType("integer");

                    b.Property<string>("DepartureBaggageStatus")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FlightPassengerId")
                        .HasColumnType("integer");

                    b.Property<int?>("HhtId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOnward")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPassengerBoarded")
                        .HasColumnType("boolean");

                    b.Property<string>("OffloadReason")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.Property<string>("RushReason")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("SourceAirportCode")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<char>("SourceIndicator")
                        .HasMaxLength(1)
                        .HasColumnType("character(1)");

                    b.Property<string>("TagNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<char?>("WeightIndicator")
                        .HasMaxLength(1)
                        .HasColumnType("character(1)");

                    b.HasKey("Id");

                    b.HasIndex("FlightPassengerId", "TagNumber");

                    b.ToTable("DepartureBags", "bags");
                });

            modelBuilder.Entity("Domain.Aggregates.Bags.DepartureBagEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BagId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int?>("DeviceId")
                        .HasColumnType("integer");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("EventTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("MessageId")
                        .HasColumnType("bigint");

                    b.Property<string>("UserName")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("BagId");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("BagId"), new[] { "EventId", "Description", "UserName", "EventTime" });

                    b.ToTable("DepartureBagEvents", "bags");
                });

            modelBuilder.Entity("Domain.Aggregates.Bags.DepartureFlightPassenger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<int>("FlightId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsOnward")
                        .HasColumnType("boolean");

                    b.Property<string>("PassengerName")
                        .IsRequired()
                        .HasMaxLength(55)
                        .HasColumnType("character varying(55)");

                    b.Property<string>("PassengerStatus")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.Property<string>("Seat")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("SecurityNumber")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("SequenceNumber")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.HasKey("Id");

                    b.HasIndex("FlightId");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("FlightId"), new[] { "Id" });

                    b.HasIndex("FlightId", "SecurityNumber")
                        .IsUnique()
                        .HasFilter("\"SecurityNumber\" IS NOT NULL");

                    b.HasIndex("FlightId", "SequenceNumber")
                        .IsUnique()
                        .HasFilter("\"SequenceNumber\" IS NOT NULL");

                    b.ToTable("DepartureFlightPassengers", "bags");
                });

            modelBuilder.Entity("Domain.Aggregates.Companies.Company", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("citext")
                        .HasColumnName("Code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("citext");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Code");

                    b.ToTable("Companies", "references");
                });

            modelBuilder.Entity("Domain.Aggregates.Containers.ContainerType", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(1)
                        .HasColumnType("citext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IsAllDestination")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTransfer")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Code");

                    b.ToTable("ContainerTypes", "references");
                });

            modelBuilder.Entity("Domain.Aggregates.Containers.ContainerTypeClass", b =>
                {
                    b.Property<string>("TypeCode")
                        .HasMaxLength(1)
                        .HasColumnType("citext")
                        .HasColumnName("TypeCode");

                    b.Property<string>("ClassCode")
                        .HasMaxLength(1)
                        .HasColumnType("citext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TypeCode", "ClassCode");

                    b.ToTable("ContainerTypeClasses", "references");
                });

            modelBuilder.Entity("Domain.Aggregates.Flights.ArrivalFlight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActualDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AirlineCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("citext");

                    b.Property<string>("Carousel")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime?>("EstimatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FlightIataDate")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("citext");

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("citext");

                    b.Property<string>("FlightStatus")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.Property<string>("HandlingCompanyCode")
                        .HasColumnType("citext");

                    b.Property<string>("IntDom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OriginAirport")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("ParkingPosition")
                        .HasColumnType("text");

                    b.Property<string>("PreviousAirport")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("Registration")
                        .HasColumnType("text");

                    b.Property<string>("RemoteSystemId")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("citext");

                    b.Property<DateTime>("ScheduledDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Terminal")
                        .HasColumnType("text");

                    b.Property<int>("TotalPassengers")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HandlingCompanyCode");

                    b.HasIndex("RemoteSystemId")
                        .IsUnique();

                    b.HasIndex("AirlineCode", "FlightNumber", "FlightIataDate");

                    b.ToTable("ArrivalFlights", "flights");
                });

            modelBuilder.Entity("Domain.Aggregates.Flights.Container", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContainerClassCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContainerCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContainerDestination")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContainerStatusCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContainerTypeCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FlightId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FlightId");

                    b.ToTable("DepartureFlightContainers", "flights");
                });

            modelBuilder.Entity("Domain.Aggregates.Flights.DepartureFlight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActualDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AirlineCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("citext");

                    b.Property<string>("CheckIn")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("CheckInStatus")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.Property<string>("Chute")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("DestinationAirport")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateTime?>("EstimatedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FlightIataDate")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("citext");

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("citext");

                    b.Property<string>("FlightStatus")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.Property<string>("Gate")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("GateStatus")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.Property<string>("HandlingCompanyCode")
                        .HasColumnType("citext");

                    b.Property<string>("IntDom")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.Property<string>("NextAirport")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("ParkingPosition")
                        .HasColumnType("text");

                    b.Property<string>("Registration")
                        .HasColumnType("text");

                    b.Property<string>("RemoteSystemId")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("citext");

                    b.Property<DateTime>("ScheduledDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Terminal")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("TotalPassengers")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HandlingCompanyCode");

                    b.HasIndex("RemoteSystemId")
                        .IsUnique();

                    b.HasIndex("AirlineCode", "FlightNumber", "FlightIataDate");

                    b.ToTable("DepartureFlights", "flights");
                });

            modelBuilder.Entity("Domain.Aggregates.HHTs.HandheldTerminal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AssignedCompanyCode")
                        .HasColumnType("citext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("citext");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("citext");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(100)
                        .HasColumnType("citext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedCompanyCode");

                    b.HasIndex("DeviceId")
                        .IsUnique();

                    b.ToTable("Hhts", "references");
                });

            modelBuilder.Entity("Domain.Aggregates.HandlingContracts.AirlineHandlingContract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AirlineCode")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("HandlingCompanyCode")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ValidTo")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("HandlingCompanyCode");

                    b.HasIndex("AirlineCode", "IsActive");

                    b.HasIndex("ValidFrom", "ValidTo");

                    b.ToTable("AirlineHandlingContracts", "references");
                });

            modelBuilder.Entity("Domain.Aggregates.HandlingContracts.AirlineHandlingContractFlightNumber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ContractId")
                        .HasColumnType("integer");

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.HasKey("Id");

                    b.HasIndex("ContractId", "FlightNumber")
                        .IsUnique();

                    b.ToTable("AirlineHandlingContractFlightNumbers", "flights");
                });

            modelBuilder.Entity("Domain.Aggregates.Mappings.AirlineClassMap", b =>
                {
                    b.Property<string>("AirlineCode")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<char>("SourceClass")
                        .HasMaxLength(1)
                        .HasColumnType("character(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<char>("TargetClass")
                        .HasMaxLength(1)
                        .HasColumnType("character(1)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("AirlineCode", "SourceClass");

                    b.HasIndex("AirlineCode", "SourceClass");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("AirlineCode", "SourceClass"), new[] { "TargetClass" });

                    b.ToTable("AirlineClassMap", "references");
                });

            modelBuilder.Entity("Domain.Aggregates.Mappings.ResourceStatusMap", b =>
                {
                    b.Property<string>("SourceResourceName")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SourceResourceStatus")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TargetResourceStatus")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.HasKey("SourceResourceName", "SourceResourceStatus");

                    b.ToTable("ResourceMaps", "references");
                });

            modelBuilder.Entity("Domain.Aggregates.Permissions.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Group");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Permissions", "references");
                });

            modelBuilder.Entity("Domain.Aggregates.Reconciliations.ArrivalFlightReconciliation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DeliveredBagCount")
                        .HasColumnType("integer");

                    b.Property<int>("ExpectedBagCount")
                        .HasColumnType("integer");

                    b.Property<int>("FlightId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsFinal")
                        .HasColumnType("boolean");

                    b.Property<int>("MissingBagCount")
                        .HasColumnType("integer");

                    b.Property<int>("RemainingOnAircraftBagCount")
                        .HasColumnType("integer");

                    b.Property<int>("RushBagCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SnapshotAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ToBeltBagCount")
                        .HasColumnType("integer");

                    b.Property<int>("TransferBagCount")
                        .HasColumnType("integer");

                    b.Property<int>("UnknownBagCount")
                        .HasColumnType("integer");

                    b.Property<int>("UnloadedBagCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FlightId")
                        .IsUnique();

                    b.ToTable("ArrivalFlightReconciliations", "bags");
                });

            modelBuilder.Entity("Domain.Aggregates.Reconciliations.DepartureFlightReconciliation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ExpectedBagCount")
                        .HasColumnType("integer");

                    b.Property<int>("FlightId")
                        .HasColumnType("integer");

                    b.Property<int>("ForceLoadedBagCount")
                        .HasColumnType("integer");

                    b.Property<bool>("IsFinal")
                        .HasColumnType("boolean");

                    b.Property<int>("LoadedBagCount")
                        .HasColumnType("integer");

                    b.Property<int>("MissingBagCount")
                        .HasColumnType("integer");

                    b.Property<int>("NotBoardedPassengerBagCount")
                        .HasColumnType("integer");

                    b.Property<int>("OffloadedCount")
                        .HasColumnType("integer");

                    b.Property<int>("OnwardBagCount")
                        .HasColumnType("integer");

                    b.Property<int>("PriorityBagCount")
                        .HasColumnType("integer");

                    b.Property<int>("ReconciledBagCount")
                        .HasColumnType("integer");

                    b.Property<int>("RushBagCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SnapshotAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ToBeOffloadedCount")
                        .HasColumnType("integer");

                    b.Property<int>("TransferLoadedBagCount")
                        .HasColumnType("integer");

                    b.Property<int>("TransferMissingBagCount")
                        .HasColumnType("integer");

                    b.Property<int>("WaitingToLoadBagCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FlightId")
                        .IsUnique();

                    b.ToTable("DepartureFlightReconciliations", "bags");
                });

            modelBuilder.Entity("Domain.Aggregates.Reconciliations.ReconciliationRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ClosedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TotalChecked")
                        .HasColumnType("integer");

                    b.Property<int>("TotalLoaded")
                        .HasColumnType("integer");

                    b.Property<int>("TotalOffloaded")
                        .HasColumnType("integer");

                    b.Property<int>("TotalTransferred")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ReconciliationRecordSet");
                });

            modelBuilder.Entity("Domain.Aggregates.Roles.Role", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("citext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Name");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles", "references");
                });

            modelBuilder.Entity("Domain.Aggregates.Roles.RolePermission", b =>
                {
                    b.Property<string>("RoleName")
                        .HasColumnType("citext");

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RoleName", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions", "references");
                });

            modelBuilder.Entity("Domain.Aggregates.Settings.SystemConfiguration", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(25)
                        .HasColumnType("citext")
                        .HasColumnName("Key");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Key");

                    b.ToTable("SystemConfigurations", "references");
                });

            modelBuilder.Entity("Domain.Aggregates.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyCode")
                        .IsRequired()
                        .HasColumnType("citext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("citext");

                    b.HasKey("Id");

                    b.HasIndex("CompanyCode");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", "references");
                });

            modelBuilder.Entity("Domain.Aggregates.Users.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("RoleName")
                        .HasColumnType("citext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleName");

                    b.HasIndex("RoleName");

                    b.ToTable("UserRoles", "references");
                });

            modelBuilder.Entity("Domain.Audits.AirlineClassMapLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PrimaryKey")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Snapshot")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Action", "Timestamp");

                    b.ToTable("AirlineClassMapLog", "audits");
                });

            modelBuilder.Entity("Domain.Audits.AirlineHandlingContractFlightNumberLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PrimaryKey")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Snapshot")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Action", "Timestamp");

                    b.ToTable("AirlineHandlingContractFlightNumberLog", "audits");
                });

            modelBuilder.Entity("Domain.Audits.AirlineHandlingContractLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PrimaryKey")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Snapshot")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Action", "Timestamp");

                    b.ToTable("AirlineHandlingContractLog", "audits");
                });

            modelBuilder.Entity("Domain.Audits.ArrivalFlightLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PrimaryKey")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Snapshot")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Action", "Timestamp");

                    b.ToTable("ArrivalFlightLog", "audits");
                });

            modelBuilder.Entity("Domain.Audits.CompanyLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PrimaryKey")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Snapshot")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Action", "Timestamp");

                    b.ToTable("CompanyLog", "audits");
                });

            modelBuilder.Entity("Domain.Audits.ContainerLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PrimaryKey")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Snapshot")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Action", "Timestamp");

                    b.ToTable("ContainerLog", "audits");
                });

            modelBuilder.Entity("Domain.Audits.ContainerTypeClassLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PrimaryKey")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Snapshot")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Action", "Timestamp");

                    b.ToTable("ContainerTypeClassLog", "audits");
                });

            modelBuilder.Entity("Domain.Audits.ContainerTypeLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PrimaryKey")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Snapshot")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Action", "Timestamp");

                    b.ToTable("ContainerTypeLog", "audits");
                });

            modelBuilder.Entity("Domain.Audits.DepartureFlightLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PrimaryKey")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Snapshot")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Action", "Timestamp");

                    b.ToTable("DepartureFlightLog", "audits");
                });

            modelBuilder.Entity("Domain.Audits.HandheldTerminalLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PrimaryKey")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Snapshot")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Action", "Timestamp");

                    b.ToTable("HandheldTerminalLog", "audits");
                });

            modelBuilder.Entity("Domain.Audits.PermissionLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PrimaryKey")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Snapshot")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Action", "Timestamp");

                    b.ToTable("PermissionLog", "audits");
                });

            modelBuilder.Entity("Domain.Audits.ResourceStatusMapLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PrimaryKey")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Snapshot")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Action", "Timestamp");

                    b.ToTable("ResourceStatusMapLog", "audits");
                });

            modelBuilder.Entity("Domain.Audits.RoleLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PrimaryKey")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Snapshot")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Action", "Timestamp");

                    b.ToTable("RoleLog", "audits");
                });

            modelBuilder.Entity("Domain.Audits.SystemConfigurationLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PrimaryKey")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Snapshot")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Action", "Timestamp");

                    b.ToTable("SystemConfigurationLog", "audits");
                });

            modelBuilder.Entity("Domain.Audits.UserLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PrimaryKey")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Snapshot")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Action", "Timestamp");

                    b.ToTable("UserLog", "audits");
                });

            modelBuilder.Entity("IataText.Parser.Entities.ElementError", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ErrorCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR")
                        .HasColumnOrder(2);

                    b.Property<string>("ErrorDescription")
                        .HasMaxLength(250)
                        .HasColumnType("VARCHAR")
                        .HasColumnOrder(3);

                    b.Property<long>("MessageId")
                        .HasColumnType("BIGINT")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("RecordDateTime")
                        .HasColumnType("TIMESTAMPTZ")
                        .HasColumnOrder(4);

                    b.HasKey("Id")
                        .HasName("PK_ElementErrorId");

                    b.ToTable("ElementErrors", "messages");
                });

            modelBuilder.Entity("IataText.Parser.Entities.TextMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Completed")
                        .HasColumnType("boolean")
                        .HasColumnOrder(9);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(5);

                    b.Property<DateTime?>("ProcessDateTime")
                        .HasColumnType("TIMESTAMPTZ")
                        .HasColumnOrder(10);

                    b.Property<DateTime?>("ProcessingStartedAt")
                        .HasColumnType("TIMESTAMPTZ")
                        .HasColumnOrder(8);

                    b.Property<DateTime>("RecordDateTime")
                        .HasColumnType("TIMESTAMPTZ")
                        .HasColumnOrder(11);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(6);

                    b.HasKey("Id")
                        .HasName("PK_TextMessageId");

                    b.HasIndex("Status", "Completed");

                    b.ToTable("TextMessages", "messages");
                });

            modelBuilder.Entity("IataText.Parser.Entities.TextMessageError", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ErrorCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR")
                        .HasColumnOrder(2);

                    b.Property<string>("ErrorDescription")
                        .HasMaxLength(250)
                        .HasColumnType("VARCHAR")
                        .HasColumnOrder(3);

                    b.Property<long>("MessageId")
                        .HasColumnType("BIGINT")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("RecordDateTime")
                        .HasColumnType("TIMESTAMPTZ")
                        .HasColumnOrder(4);

                    b.HasKey("Id")
                        .HasName("PK_MessageErrorId");

                    b.ToTable("MessageErrors", "messages");
                });

            modelBuilder.Entity("Domain.Aggregates.Bags.ArrivalBag", b =>
                {
                    b.HasOne("Domain.Aggregates.Bags.ArrivalFlightPassenger", "FlightPassenger")
                        .WithMany()
                        .HasForeignKey("FlightPassengerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("FlightPassenger");
                });

            modelBuilder.Entity("Domain.Aggregates.Bags.ArrivalBagEvent", b =>
                {
                    b.HasOne("Domain.Aggregates.Bags.ArrivalBag", "ArrivalBag")
                        .WithMany()
                        .HasForeignKey("BagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArrivalBag");
                });

            modelBuilder.Entity("Domain.Aggregates.Bags.ArrivalFlightPassenger", b =>
                {
                    b.HasOne("Domain.Aggregates.Flights.ArrivalFlight", "Flight")
                        .WithMany()
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flight");
                });

            modelBuilder.Entity("Domain.Aggregates.Bags.DepartureBag", b =>
                {
                    b.HasOne("Domain.Aggregates.Bags.DepartureFlightPassenger", "FlightPassenger")
                        .WithMany()
                        .HasForeignKey("FlightPassengerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("FlightPassenger");
                });

            modelBuilder.Entity("Domain.Aggregates.Bags.DepartureBagEvent", b =>
                {
                    b.HasOne("Domain.Aggregates.Bags.DepartureBag", "DepartureBag")
                        .WithMany()
                        .HasForeignKey("BagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DepartureBag");
                });

            modelBuilder.Entity("Domain.Aggregates.Bags.DepartureFlightPassenger", b =>
                {
                    b.HasOne("Domain.Aggregates.Flights.DepartureFlight", "Flight")
                        .WithMany()
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flight");
                });

            modelBuilder.Entity("Domain.Aggregates.Flights.ArrivalFlight", b =>
                {
                    b.HasOne("Domain.Aggregates.Companies.Company", "HandlingCompany")
                        .WithMany()
                        .HasForeignKey("HandlingCompanyCode")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("HandlingCompany");
                });

            modelBuilder.Entity("Domain.Aggregates.Flights.DepartureFlight", b =>
                {
                    b.HasOne("Domain.Aggregates.Companies.Company", "HandlingCompany")
                        .WithMany()
                        .HasForeignKey("HandlingCompanyCode")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("HandlingCompany");
                });

            modelBuilder.Entity("Domain.Aggregates.HHTs.HandheldTerminal", b =>
                {
                    b.HasOne("Domain.Aggregates.Companies.Company", "AssignedCompany")
                        .WithMany()
                        .HasForeignKey("AssignedCompanyCode")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AssignedCompany");
                });

            modelBuilder.Entity("Domain.Aggregates.HandlingContracts.AirlineHandlingContract", b =>
                {
                    b.HasOne("Domain.Aggregates.Companies.Company", "HandlingCompany")
                        .WithMany()
                        .HasForeignKey("HandlingCompanyCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HandlingCompany");
                });

            modelBuilder.Entity("Domain.Aggregates.HandlingContracts.AirlineHandlingContractFlightNumber", b =>
                {
                    b.HasOne("Domain.Aggregates.HandlingContracts.AirlineHandlingContract", null)
                        .WithMany("FlightNumbers")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Aggregates.Reconciliations.ArrivalFlightReconciliation", b =>
                {
                    b.HasOne("Domain.Aggregates.Flights.ArrivalFlight", null)
                        .WithMany("ReconciliationRecords")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Aggregates.Reconciliations.DepartureFlightReconciliation", b =>
                {
                    b.HasOne("Domain.Aggregates.Flights.DepartureFlight", null)
                        .WithMany("ReconciliationRecords")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Aggregates.Roles.RolePermission", b =>
                {
                    b.HasOne("Domain.Aggregates.Permissions.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Aggregates.Roles.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Domain.Aggregates.Users.User", b =>
                {
                    b.HasOne("Domain.Aggregates.Companies.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Domain.Aggregates.Users.UserRole", b =>
                {
                    b.HasOne("Domain.Aggregates.Roles.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleName")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Aggregates.Users.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IataText.Parser.Entities.TextMessage", b =>
                {
                    b.OwnsOne("IataText.Parser.ValueObjects.MessageFooter", "Footer", b1 =>
                        {
                            b1.Property<long>("TextMessageId")
                                .HasColumnType("BIGINT");

                            b1.Property<string>("EndIdentifier")
                                .IsRequired()
                                .HasMaxLength(6)
                                .HasColumnType("VARCHAR")
                                .HasColumnOrder(4);

                            b1.HasKey("TextMessageId");

                            b1.ToTable("TextMessages", "messages");

                            b1.WithOwner()
                                .HasForeignKey("TextMessageId");
                        });

                    b.OwnsOne("IataText.Parser.ValueObjects.MessageHeader", "Header", b1 =>
                        {
                            b1.Property<long>("TextMessageId")
                                .HasColumnType("BIGINT");

                            b1.Property<string>("ChangeOfStatus")
                                .HasMaxLength(3)
                                .HasColumnType("VARCHAR")
                                .HasColumnOrder(3);

                            b1.Property<string>("Identifier")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("VARCHAR")
                                .HasColumnOrder(1);

                            b1.Property<string>("SecondaryIdentifier")
                                .HasMaxLength(3)
                                .HasColumnType("VARCHAR")
                                .HasColumnOrder(2);

                            b1.HasKey("TextMessageId");

                            b1.HasIndex("Identifier", "SecondaryIdentifier", "ChangeOfStatus");

                            b1.ToTable("TextMessages", "messages");

                            b1.WithOwner()
                                .HasForeignKey("TextMessageId");
                        });

                    b.Navigation("Footer")
                        .IsRequired();

                    b.Navigation("Header")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Aggregates.Flights.ArrivalFlight", b =>
                {
                    b.Navigation("ReconciliationRecords");
                });

            modelBuilder.Entity("Domain.Aggregates.Flights.DepartureFlight", b =>
                {
                    b.Navigation("ReconciliationRecords");
                });

            modelBuilder.Entity("Domain.Aggregates.HandlingContracts.AirlineHandlingContract", b =>
                {
                    b.Navigation("FlightNumbers");
                });

            modelBuilder.Entity("Domain.Aggregates.Permissions.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Domain.Aggregates.Roles.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Domain.Aggregates.Users.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
